language: javascript

sudo: required

services:
  - docker

branches:
  only:
    - master

before_install:
  - sudo apt-get update
  - sudo apt-get install jq
  - docker pull berrywallet/site:latest

script:
  - NODE_ENV=production
  - BW_ENV=production
  - export APPLICATION_VERSION=$(jq -r ".version" package.json)
  - docker build --file ./Dockerfile --tag berrywallet/site:$APPLICATION_VERSION --tag berrywallet/site .
  - docker login --username "$DOCKER_USERNAME" --password "$DOCKER_PASSWORD"
  - docker push berrywallet/site:$APPLICATION_VERSION
  - docker push berrywallet/site:latest