language: javascript

sudo: required

services:
  - docker

branches:
  only:
    - master

before_install:
  - sudo apt-get update
  - sudo apt-get install jq
  - docker pull berrywallet/site:latest

script: bash ./build/build-container.sh

# deploy:
#   provider: script
#   script: bash build-container.sh
#   on:
#     branch: master