version: '3.1'

services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: berrywallet-site
    ports:
      - 5432:5432
  adminer:
    image: meedan/pgadmin
    restart: always
    links:
      - postgres:postgres
    ports:
      - 5050:5050
