version: '3.1'

services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: berrywallet-site
  adminer:
    image: meedan/pgadmin
    restart: always
    links:
      - postgres:postgres
    ports:
      - 5050:5050
  site:
    image: berrywallet/site
    restart: always
    links:
      - postgres:postgres
    ports:
      - 3000:3000
    environment:
      DB_HOST: postgres
      DB_USER: postgres
      DB_PASS: password
      DB_NAME: berrywallet-site
    depends_on:
      - postgres